### ISSUE TITLE
Clock gets stuck, sometimes

### ISSUE THREAD

**Issue by hlolli** [2bbb/node-abletonlink#1]
Hi, thanks for this great library. I want to use the clock to reference schedules. I set Abletonlink.startUpdate to 10ms and on each function callback I send the timestamp from beat (of beat,phase and bpm that coma available as parameters). I printed to console an example of this (excuse the noise and ignore "offering:" part of the printout).
```

"offering: " 658.126638
"offering: " 658.147352
"offering: " 658.168396
"offering: " 658.189242
"offering: " 658.209964
"offering: " 658.230772
"offering: " 658.251438
"offering: " 658.272136
"offering: " 658.292854
"offering: " 658.313632
"offering: " 658.334332
"offering: " 658.355062
"offering: " 658.375954
"offering: " 658.396834
"offering: " 658.417746
"offering: " 658.440108
"offering: " 658.460968
"offering: " 658.48173
"offering: " 658.500564
"offering: " 658.521474
"offering: " 658.543846
"offering: " 658.562602
"offering: " 658.583232
"offering: " 658.604882
"offering: " 658.625718
"offering: " 658.648232
"offering: " 658.669106
"offering: " 658.689856
"offering: " 658.71058
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
"offering: " 658.775808
```
this lasts for on avarage 30 secs, then it start counting normally again. I wonder if there's some concurrency issues with the clock and nodejs. Must add that I'm not doing anything special when this occours. No steps to reproduce but to just start console.logging the beat value from .startUpdate and wait until it clogs.

Im using 
Node 7.0.0
abletonliink 0.0.3

**Comment by 2bbb** [comment]
@hlolli 
thanks for issue.

i tried to check on `v6.9` with code:

```
const abletonlink = require('abletonlink');

const link = new abletonlink();

console.log("start\a");
let last = 0;
link.startUpdate(10, beat => {
    console.log(beat);
    if(last == beat) throw "WTF";
    last = beat;
});
```

but it doesn't happen.

now, i'm testing on `v7.0`. but maybe it will not happen...

do you use on Mac? or other? and OS version?
please tell me your env.

thanks.

**Comment by hlolli** [comment]
I got `WTF` with your code you provided, just from the node repl.
```
60.423198
60.44378
60.465106
60.485588
60.506462
60.52806
60.548614
60.569372
60.591674
60.61231
60.633042
60.654306
60.675272
60.697764
60.718366
60.73904
58.775808
58.775808
WTF
> 
```
I use Linux Fedora 25. Ususally Im making a clojurescript project as can be seen here https://github.com/hlolli/node-panaeolus/ seemingly that's not a factor here. I'd be curious to see what happens on node7.0 for you. Thanks for looking into this!

**Comment by 2bbb** [comment]
mmm...
on v7.0.0, it didn't happen...

but i got good news.
it is this package is moving on Linux! :+1:
(but behavior is doubtful...)

i will try to test on linux.
maybe there is ubuntu machine at my company...
and i will pay attention to `.775808` 😉 

thanks.

**Comment by 2bbb** [comment]
@hlolli 

i tested on Fedora25 and Ubuntu16.04 with Node7.0.0 while 2 hours.
it didin't happen on Ubuntu16.04.

but, Fedora25 got same situation with 

```
1379.540556
1379.561542
1379.582414
1379.603904
1379.62518
1379.64751
1379.669972
1379.693238
1379.714658
1379.735916
1378.775808
1378.775808
```

oh, yeah, `.775808` is appear!!

but i don't know what i need to do to fix it...

i will test raw abletonlink (i.e. without Node.js, only c++) on Fedora25.
if it will happen, then maybe it is cause on abletonlink or Fedora25.

best regards.

**Comment by hlolli** [comment]
ok, thanks a lot @2bbb for going the distance and set up a fedora docker, that's real!

I have short performance later this month, so I see I have the option of changing to Ubuntu or find the cause of this strange bug. Look forward to see what results you get with pure c++.

best regards.

**Comment by 2bbb** [comment]
@hlolli 

so, on previous test, gcc version is not same.

* Ubuntu 16.04 with gcc 4.9.4
* Fedora 25 with gcc 6.2.1

and now, i tested on docker/Ubuntu with near version gcc 6.2.0 (there isn't 6.2.1 on apt...).
but it didn't happen.

maybe, using Ubuntu is safety.
but maybe switching to Ubuntu is hard work... 😭

i wanna support you! i will test pure c++ 😄

**Comment by hlolli** [comment]
I want to switch to NixOS in the long run (but that is very diffucult linux), but for one performance I can borrow my some computer.

If you find out that pure c++ fails, then we can open a ticket on AbletonLink and see if they can find out what's going on. I can't understand why Fedora is causing this, maybe some c/c++ library that AbletonLink uses, that is on default installed on fedora, is causing this, don't know....

I would support you back in german beers :D but not sure how well they taste after traveling to Japan

**Comment by 2bbb** [comment]
maybe ableton link use only pure C++11.
and dependencie are only simple C++ library, `asio standalone` and `Catch`.
they have no dependencies to other library.
and all source is include to this package and build when `npm install`.

so, this is difficult situation...

i love german beers! only one time, i went karlsruhe and i drunk tasty beer on reception of z.k.m. it is great!! :100:

**Comment by 2bbb** [comment]
now testing pure c++ on Fedora25...

i upload build script and cpp file.

https://gist.github.com/2bbb/38dcb04f99aef24a241276293f89924e/

download to directory includes `node_modules/abletonlink` and exec `build.sh`.
then we got `link.o`, and run `./link.o`

**Comment by 2bbb** [comment]
on Fedora, pure C++ program didn't get stack.
and i test on node.js with 20ms interval, then it didn't get stack.

maybe, it is causes on my source code or Node.js on Fedora...

mmm...

**Comment by hlolli** [comment]
I will have to try this when I get back home late tonigh, but at my work computer (also Fedora25) I tried the c++ code you wrote, it didn't fail, but there's some difference in how the floats are rounded. Also the nodejs hasn't failed to far (I have it running here). I keep updated.

**Comment by 2bbb** [comment]
@hlolli 

> there's some difference in how the floats are rounded
exactly! but in my C++ code, every data keep with `double`, and maybe basically, node's Number is `double`. (sometime, it isn't `double`, like ByteArray and etc..,)

but, `console.log(beat.toPrecision(21));` say similar result as C++.

**Comment by hlolli** [comment]
Hmm ok.., so it's not that. I'm tempted to close this as non-resolveable. I wasn't able to get `WTF` showing up at my work computer and its Fedora25. I try the C++ code at home and 20ms interval if that makes any change. Let you know tonight (guessing it will be nighttime in Japan).

**Comment by hlolli** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/6074754/23628614/222324d2-02b5-11e7-84e3-f105b510e957.jpeg)
On the left side is the c++ code running forever and on the right nodejs having complications. This isn't anything new, maybe we can close this. For my part, I'm going to install new linux distro, Im also having other complications with Fedora, and I don't think its going to be too diffucult to change. Yet again, thanks for looking into this.

**Comment by 2bbb** [comment]
@hlolli 

thanks for testing on your env.

and i'm sorry for i was unable to be of any assistance.

i wanna resolve this problem in the future and i will keep to try.

thanks!

**Comment by hlolli** [comment]
I just tested the nodejs code on Fedora25 on Kernel 4.9.9 and I don't experience these stops. But this Kernel is not the realtime kernel, which so far I only tested with. So maybe this is just a deeper problem of V8 engine and rt-kernel. I'm at 1700th tick and nothing is getting stuck, which is good news.

**Comment by 2bbb** [comment]
@hlolli 

oh yeah!! it is good news!

but, a little bad news at the same time...
because if really problem is under V8 and rt-kernel, i can't do anything... 😢

**Comment by hlolli** [comment]
Yup, and lowering the nice value in rt-kernel prevents the clock from getting stuck.

Think we can close this.
