### ISSUE TITLE
Issues installing

### ISSUE THREAD

**Issue by saebekassebil** [2bbb/node-abletonlink#11]
Hello @2bbb !

This is a super exciting project and I'd really like to use it in my setup, but I'm having troubles building the module after installing it (with npm)

I get the following errors:
```
In file included from ../src/nbind.cc:1:
In file included from ../src/./node-abletonlink.hpp:13:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:193:1: error: too few arguments to function call, single argument 'context' was not
      specified

In file included from ../src/nbind.cc:1:
In file included from ../src/./node-abletonlink.hpp:13:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:71:
../../nbind/include/nbind/v8/BindWrapper.h:217:38: error: expected '(' for function-style cast or type construction
                void *ptr = v8::Handle<v8::External>::Cast(nanArgs[0])->Value();
                                       ~~~~~~~~~~~~^
../../nbind/include/nbind/v8/BindWrapper.h:217:19: error: no member named 'Handle' in namespace 'v8'
                void *ptr = v8::Handle<v8::External>::Cast(nanArgs[0])->Value();
                            ~~~~^
../../nbind/include/nbind/v8/BindWrapper.h:217:41: error: no member named 'Cast' in the global namespace
                void *ptr = v8::Handle<v8::External>::Cast(nanArgs[0])->Value();
                                                    ~~^
../../nbind/include/nbind/v8/BindWrapper.h:217:19: error: 'handle_' is a private member of 'node::ObjectWrap'
                void *ptr = v8::Handle<v8::External>::Cast(nanArgs[0])->Value();
```

and many others. Have I overlooked some dependency, or is this something else? I'm building on macOS Catalina 10.15.4

**Comment by 2bbb** [comment]
please tell me your node version.

**Comment by Onni97** [comment]
> 
> 
> Hello @2bbb !
> 
> This is a super exciting project and I'd really like to use it in my setup, but I'm having troubles building the module after installing it (with npm)
> 
> I get the following errors:
> 
> ```
> In file included from ../src/nbind.cc:1:
> In file included from ../src/./node-abletonlink.hpp:13:
> In file included from ../../nbind/include/nbind/nbind.h:8:
> In file included from ../../nbind/include/nbind/noconflict.h:8:
> In file included from ../../nbind/include/nbind/BindDefiner.h:11:
> In file included from ../../nbind/include/nbind/api.h:72:
> ../../nbind/include/nbind/v8/BindingType.h:193:1: error: too few arguments to function call, single argument 'context' was not
>       specified
> 
> In file included from ../src/nbind.cc:1:
> In file included from ../src/./node-abletonlink.hpp:13:
> In file included from ../../nbind/include/nbind/nbind.h:8:
> In file included from ../../nbind/include/nbind/noconflict.h:8:
> In file included from ../../nbind/include/nbind/BindDefiner.h:11:
> In file included from ../../nbind/include/nbind/api.h:71:
> ../../nbind/include/nbind/v8/BindWrapper.h:217:38: error: expected '(' for function-style cast or type construction
>                 void *ptr = v8::Handle<v8::External>::Cast(nanArgs[0])->Value();
>                                        ~~~~~~~~~~~~^
> ../../nbind/include/nbind/v8/BindWrapper.h:217:19: error: no member named 'Handle' in namespace 'v8'
>                 void *ptr = v8::Handle<v8::External>::Cast(nanArgs[0])->Value();
>                             ~~~~^
> ../../nbind/include/nbind/v8/BindWrapper.h:217:41: error: no member named 'Cast' in the global namespace
>                 void *ptr = v8::Handle<v8::External>::Cast(nanArgs[0])->Value();
>                                                     ~~^
> ../../nbind/include/nbind/v8/BindWrapper.h:217:19: error: 'handle_' is a private member of 'node::ObjectWrap'
>                 void *ptr = v8::Handle<v8::External>::Cast(nanArgs[0])->Value();
> ```
> 
> and many others. Have I overlooked some dependency, or is this something else? I'm building on macOS Catalina 10.15.4

This projects uses nbind that supports only Node 6 or older, so with newer version it doesn't work. Are you using a more recent version?
If this will help you, I'm developing an Ableton Link in node integration using native-addon-api that are supported directly from Node.

**Comment by saebekassebil** [comment]
Ah yes, hadn't seen that. I'm running node v13. Your project definitely sounds like something that would help me! Where can I find it?

Cheers!

**Comment by Onni97** [comment]
I'm finishing it. I think tomorrow I'll upload ;)

**Comment by saebekassebil** [comment]
Looking forward to it. Thank you to you both for your work.

**Comment by 2bbb** [comment]
@saebekassebil @Onni97 

thanks for pointing out and recommend node-addon-api.
I try to replace nbind with node-addon-api in dev/node-addon-api branch.

if you interested in, please check it.

**Comment by Onni97** [comment]
I'm gonna implement it by myself because it's linked with an University project. I'm finishing this today and I'll upload it if you're interested 😃
