### ISSUE TITLE
Regression: Callback_handler not run as a infinite loop, tempo changes not tracked

### ISSUE THREAD

**Issue by tbazin** [2bbb/node-abletonlink#14]
https://github.com/2bbb/node-abletonlink/blob/bc8c34499d7c7816cddab812f2d7416682bb0acb/src/napi-abletonlink.hpp#L69-L72

The `callback_handler` function should be run as an infinite loop. This was previously handled by libuv:https://github.com/2bbb/node-abletonlink/blob/8b5122f3ec8fdc3f6bae3fc7b9783a05a7f6d8f8/src/node-abletonlink.hpp#L95 but has not been replaced after the removal of libuv.

In the absence of such a loop, the callback_handler thread stops after a single run through the different update piles and stops listening to further changes thereafter.

I managed to fixed the issue by enclosing the part after the mutex request into a simple `while (true) {...` loop, but I'm not 100% certain that this would be the appropriate way of doing things since I actually have no experience whatsoever with C++ 😄 If this approach seems alright though, I'd be happy to submit this very simple PR.

**Comment by 2bbb** [comment]
@tbazin 

omg!!
i can't remember what i want to do, but maybe you are correct!
please submit PR!

thanks!
