### ISSUE TITLE
playState is still not getting updated

### ISSUE THREAD

**Issue by ktamas77** [2bbb/node-abletonlink#18]
This issue still exists -> `link.startUpdate(60, (beat, phase, bpm, playState) => {...` won't update `playState`, its always undefined.
`link.on('playState')` also never will be triggered.
However, `link.onPlayStateChanged()` works, but sadly it's not super useful as we don't know the initial state.

**Comment by alx-1** [comment]
> 

You can try reading the 'isPlaying' property with 'link.isPlaying' ?

**Comment by 2bbb** [comment]
hi @ktamas77 and @alx-1

maybe [this branch](https://github.com/2bbb/node-abletonlink/tree/dev/fix_playstate) works.
please check. if it works then I will publish to npm.

thanks

**Comment by 2bbb** [comment]
I published `0.2.0-beta.0` with update versions of dependencies.
please test with `npm i abletonlink@0.2.0-beta.0`!

**Comment by 2bbb** [comment]
maybe this problem was solved.
if there is some problems, then please Reopen.

**Comment by ktamas77** [comment]
i am sorry for the late reply - first of all thank you for fixing this issue - i'll confirm soon!

**Comment by alx-1** [comment]
Sorry for the latency, I was encountering another problem with changing the bpm and this 'npm i abletonlink@0.2.0-beta.0' fixed it :).
