### ISSUE TITLE
Succesfully compiled node-abletonlink on the raspberry pi 3 model B

### ISSUE THREAD

**Issue by CarloCattano** [2bbb/node-abletonlink#5]
Since i couldn't compile on windows I tried in my rbpi 3 and it works . 
When loading the example just need to change "let" to "var" in line 16, otherwise node wont run

**Comment by 2bbb** [comment]
it's great!

i don't know why you can't use `let`.
what version of node.js do you use?

**Comment by CarloCattano** [comment]
v4.2.1
it throwed an error when initializing node inde.js on that line , so i just replaced it an works!
Still i have latency issues since the server is synced but the client is dependent on the socket.io speed , but Its a start ! thanks again for this

**Comment by CarloCattano** [comment]
I really want to combine it with something like this  and have the clients synced , but i guess we should wait for ableton to port it for client side maybe https://github.com/CarloCattano/PopularSynth

**Comment by 2bbb** [comment]
hmmm.
i don't know why you use v4.x.
so, i don't have plan to support v4.x, i recommend to use newer one.

of course, what you choose is your freedom!
but, sorry, i can't support you if choice older one.

best regards.

**Comment by CarloCattano** [comment]
Is what I get with the version of raspbian strech and apt-get install nodejs. Thanks for the hint I'll try to install  a newer one

**Comment by 2bbb** [comment]
@CarloCattano 

maybe, is this page help you?
https://www.raspberrypi.org/forums/viewtopic.php?t=140747#p932480

**Comment by CarloCattano** [comment]
Thanks you are so kind . I was gonna google that after the second coffe :-)

**Comment by CarloCattano** [comment]
@2bbb  ??? 
![node](https://user-images.githubusercontent.com/17380530/33168898-dd91daaa-d042-11e7-82d8-84055936b809.PNG)

**Comment by 2bbb** [comment]
@CarloCattano 
sorry, i have assumed newer than v6.

**Comment by CarloCattano** [comment]
working now perfectly from v8.9.1 !
