### ISSUE TITLE
More advanced example

### ISSUE THREAD

**Issue by allforabit** [2bbb/node-abletonlink#7]
Thanks for the work on this. It works really well. I'm just wondering if there are some more advanced examples. I'm looking to implement a simple arpeggiator just a simple project to experiment with. I've setup max for live to send notes using osc, and setup node.js to send notes back (via osc). I've also got Ableton link setup in node. For the next step I'd like to generate notes on the beat for instance. It's just not all that obvious how to go about this in node.js which doesn't seem to have any accurate scheduler. I guess I could just I could just use setTimeout that adjusts based on the beat info from Ableton. Apologies I know this is more of a support request than a proper issue report.

**Comment by 2bbb** [comment]
please create example with yourself and send PR!

i will close this issue. but if you feel this thread is needed, feel free to re-open.
