### ISSUE TITLE
Run in docker container 

### ISSUE THREAD

**Issue by tatecarson** [2bbb/node-abletonlink#8]
I am trying to deploy a project with node-abletonlink and I have to use Docker. I am having some trouble getting it to work. Would it be possible to get the Dockerfile that you used to test the Ubuntu environment with?

**Comment by 2bbb** [comment]
@tatecarson 
oh... sorry for late reply.

maybe already i don't have Dockerfile i tested...
maybe it was simple. base is official Ubuntu image.
and maybe need to install gcc, python2.x and node.js only.

i will look for Dockerfile tomorrow.

**Comment by 2bbb** [comment]
@tatecarson 
i don't know. and this is not problem about this package.
